spring.application.name=VRRS

spring.datasource.url=jdbc:mariadb://localhost:3306/infodb
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# CLOVA
naver.clova.api.url=https://7j0nhtsoc4.apigw.ntruss.com/custom/v1/34153/65a86b9f3cfccf3bbddb2e56edd152f2d688776331e9b6665eeba8f7812555b0/general
naver.clova.api.secret=enNnS29nTEhneFp1Q1FOcFZQdUdKUGNYa0NnVllaUHM=